services:
  - type: web
    name: 𝐃𝐀𝐕𝐄-𝐗𝐌𝐃
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add your custom environment variables here
