services:
  - type: worker
    name: DAVE-XMD
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_ID
        value: IK~
      - key: PORT
        value: 10000
